"""initial_wardrobe_schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-15 09:22:51.292165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fabric', sa.String(), nullable=True),
    sa.Column('warmth', sa.Integer(), nullable=False),
    sa.Column('formality', sa.String(), nullable=False),
    sa.Column('season', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('warmth BETWEEN 0 AND 5', name='ck_catalog_items_warmth_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wardrobe_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fabric', sa.String(), nullable=True),
    sa.Column('warmth', sa.Integer(), nullable=False),
    sa.Column('formality', sa.String(), nullable=False),
    sa.Column('season', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), server_default='catalog', nullable=False),
    sa.Column('catalog_item_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('warmth BETWEEN 0 AND 5', name='ck_wardrobe_items_warmth_range'),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wardrobe_items_user_id'), 'wardrobe_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wardrobe_items_user_id'), table_name='wardrobe_items')
    op.drop_table('wardrobe_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
