import { createClient } from "@/lib/supabase/client";
import type { paths } from "./schema";

export class ApiError extends Error {
  constructor(
    message: string,
    public status: number,
  ) {
    super(message);
  }
}

type Method = "GET" | "PATCH";

/**
 * Thin typed fetch wrapper — types come from `schema.d.ts`, generated by
 * `npm run generate:api` from the backend's own OpenAPI schema (Constitution
 * Principle VII: no hand-written duplicate request/response shapes).
 */
export async function apiFetch<TResponse>(
  path: keyof paths,
  method: Method,
  body?: unknown,
): Promise<TResponse> {
  const supabase = createClient();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}${path}`, {
    method,
    headers: {
      "Content-Type": "application/json",
      ...(session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {}),
    },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });

  if (!response.ok) {
    throw new ApiError(`${method} ${path} failed`, response.status);
  }

  return (await response.json()) as TResponse;
}
