/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_api_v1_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/closet/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Closet Items */
        get: operations["list_closet_items_api_v1_closet_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/closet/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Closet Item */
        get: operations["get_closet_item_api_v1_closet_items__item_id__get"];
        put?: never;
        post?: never;
        /** Delete Closet Item */
        delete: operations["delete_closet_item_api_v1_closet_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Closet Item */
        patch: operations["update_closet_item_api_v1_closet_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/closet/items/{item_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Closet Item Favorite */
        post: operations["toggle_closet_item_favorite_api_v1_closet_items__item_id__favorite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/closet/items/{item_id}/wear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Closet Item Worn */
        post: operations["log_closet_item_worn_api_v1_closet_items__item_id__wear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/closet/items/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Closet Item
         * @description Draft extraction only — persists nothing to `wardrobe_items`
         *     (contracts/closet-items-extract.md, superseding contracts/wardrobe-
         *     items-extract.md's response shape). Always returns a LIST of drafts,
         *     one per detected garment, even when there's exactly one (feature 018,
         *     spec.md FR-001/FR-004) — an extension of the existing contract, not a
         *     new route. Extraction failure is always a 200 with `extraction_ok:
         *     false` on a single fallback draft; only a genuine Storage failure 5xxs
         *     (handoff §5.2, unchanged).
         */
        post: operations["extract_closet_item_api_v1_closet_items_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/closet/items/from-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Closet Item From Upload
         * @description Creates a `wardrobe_items` row from a previously-extracted (and
         *     possibly corrected) draft (contracts/closet-items-from-upload.md,
         *     superseding contracts/wardrobe-items-create-from-upload.md's field
         *     list). `ports.ClosetRepository` is unchanged — this calls a repository
         *     method beyond the Protocol, same pattern 005's four write methods
         *     already established (handoff trap 5).
         */
        post: operations["create_closet_item_from_upload_api_v1_closet_items_from_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/style-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Style Preferences */
        patch: operations["update_style_preferences_api_v1_profile_style_preferences_patch"];
        trace?: never;
    };
    "/api/v1/profile/body-size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Body Size */
        patch: operations["update_body_size_api_v1_profile_body_size_patch"];
        trace?: never;
    };
    "/api/v1/profile/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Notifications */
        patch: operations["update_notifications_api_v1_profile_notifications_patch"];
        trace?: never;
    };
    "/api/v1/calendar/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["get_connection_api_v1_calendar_connection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/connect/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Connect */
        post: operations["start_connect_api_v1_calendar_connect_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/connect/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Connect */
        post: operations["finish_connect_api_v1_calendar_connect_finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect */
        post: operations["disconnect_api_v1_calendar_disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_calendar_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/picked-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Picked Event */
        get: operations["get_picked_event_api_v1_calendar_picked_event_get"];
        /** Set Picked Event */
        put: operations["set_picked_event_api_v1_calendar_picked_event_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Category Taxonomy
         * @description `{group: [specific categories]}`. The six group names themselves are
         *     excluded — they are the keys, and offering "top" as a type within "top"
         *     would be noise. A caller that genuinely has no better answer stores the
         *     bare group name, which `categories.group_of` round-trips.
         */
        get: operations["get_category_taxonomy_api_v1_taxonomy_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Readiness */
        get: operations["get_readiness_api_v1_recommend_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Turn
         * @description feature 016, contracts/recommend-turns.md. Separate from `/recommend/messages`: no
         *     readiness gate (a conversational reply never touches wardrobe, research.md §1), no retrieval,
         *     no wardrobe load, no pipeline invocation — `graph.get_state`/`update_state` read and patch the
         *     pipeline's own per-thread checkpoint without ever calling `graph.invoke` (design-decisions.md
         *     §47). Sole writer of `user_message` rows from this feature on (§50).
         */
        post: operations["send_turn_api_v1_recommend_turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_v1_recommend_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Chat history's own list (design-system.md § Chat history) — feature
         *     011. Always `200`, `sessions: []` for the true empty case, matching
         *     every other list route's own empty-is-still-200 convention. No
         *     pagination (research.md §7) — same personal-app scale as
         *     `GET /recommend/outfits`.
         */
        get: operations["list_sessions_api_v1_recommend_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Session detail — the full read-only transcript (design-system.md §
         *     Chat history / Session detail) — feature 011. `404` (not distinguishing
         *     "doesn't exist" from "isn't yours") matches every other detail route's
         *     own convention.
         */
        get: operations["get_session_api_v1_recommend_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend/outfits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Outfits
         * @description The Outfits gallery (design-system.md § Outfits (gallery)) —
         *     feature 010. Always `200`, `outfits: []` for the true empty case (no
         *     separate empty response shape, matching 009's `outfits[]` convention
         *     for the pager).
         *
         *     Paginated the same way `closet.py`'s `list_closet_items` is (gh-28):
         *     `outfit_repository.list_outfits` still returns every row for `sort`,
         *     sliced here in Python so the same `sort` keeps producing a stable,
         *     continuable order across pages — only the current page's rows ever
         *     reach the signing call below, which is the actual cost this fixes.
         */
        get: operations["list_outfits_api_v1_recommend_outfits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend/outfits/{outfit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Outfit
         * @description Outfit detail (design-system.md § Outfit detail) — feature 010. An
         *     item id in the outfit's `item_ids` no longer present in the caller's
         *     wardrobe is silently omitted from `items` (Constitution IV — never a
         *     stale/broken reference), never an error.
         */
        get: operations["get_outfit_api_v1_recommend_outfits__outfit_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Outfit
         * @description design-decisions.md §40: confirmation is a client-side UI gate —
         *     this route performs the delete unconditionally once called, matching
         *     `DELETE /closet/items/{item_id}`'s own shape. Cascades to the outfit's
         *     `outfit_wears` rows via the migration's `on delete cascade`.
         */
        delete: operations["delete_outfit_api_v1_recommend_outfits__outfit_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend/outfits/{outfit_id}/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename Outfit
         * @description The gallery card's inline rename and the overflow sheet's "Edit
         *     title" row both call this (design-system.md § Outfits (gallery) item
         *     2). Rejects an empty/whitespace-only title (FR-006) before it ever
         *     reaches the repository.
         */
        patch: operations["rename_outfit_api_v1_recommend_outfits__outfit_id__title_patch"];
        trace?: never;
    };
    "/api/v1/recommend/outfits/{outfit_id}/wear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Outfit Worn
         * @description design-decisions.md §39: logs the outfit itself as worn today AND
         *     every item in it the caller still owns, via `SupabaseOutfitRepository.
         *     log_worn`. Idempotent — a repeat call the same calendar day is a
         *     no-op success, not an error (FR-005).
         */
        post: operations["log_outfit_worn_api_v1_recommend_outfits__outfit_id__wear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommend/outfits/{outfit_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle Outfit Favorite
         * @description The heart's second tap onward — flips the same `favorite` flag the
         *     first tap set to `true`; never deletes the row (design-decisions.md
         *     §32). `404` (not distinguishing "doesn't exist" from "isn't yours") for
         *     the same reason `toggle_closet_item_favorite` doesn't either.
         */
        post: operations["toggle_outfit_favorite_api_v1_recommend_outfits__outfit_id__favorite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthorizeUrlResponse */
        AuthorizeUrlResponse: {
            /** Authorize Url */
            authorize_url: string;
        };
        /** BodySizeUpdate */
        BodySizeUpdate: {
            /** Body Shape */
            body_shape?: string | null;
            /** Gender */
            gender?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Height */
            height?: string | null;
            /** Top Size */
            top_size?: string | null;
            /** Bottom Size */
            bottom_size?: string | null;
            /** Shoe Size */
            shoe_size?: string | null;
        };
        /** Body_extract_closet_item_api_v1_closet_items_extract_post */
        Body_extract_closet_item_api_v1_closet_items_extract_post: {
            /** Photo */
            photo: string;
        };
        /**
         * BoundingBox
         * @description A detection's region within the original photo, as fractions of its
         *     width/height (0-1) — resolution-independent, so the frontend applies it
         *     against the browser's own naturalWidth/naturalHeight rather than the
         *     backend needing to know the display size (specs/018-photo-to-items/
         *     research.md §4). `{0,0,1,1}` means "the whole photo" — the fallback
         *     region for the single-draft cases vision.detect_garments_from_image
         *     never itself constructs (that's the route's job, see closet.py).
         */
        BoundingBox: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** CalendarEventView */
        CalendarEventView: {
            /** Google Event Id */
            google_event_id: string;
            /** Title */
            title: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Location */
            location: string | null;
        };
        /**
         * CitedRuleView
         * @description One row of Outfit detail's numbered styling-rules list — the
         *     footnote a `[n]` marker in `rationale_with_citations` points at.
         */
        CitedRuleView: {
            /** Number */
            number: number;
            /** Text */
            text: string;
        };
        /**
         * ClosetItemEditRequest
         * @description Route-local edit-form body — deliberately not `WardrobeItemPatch`
         *     itself. Every field optional (partial update); `colors_text` is the
         *     one bridge `WardrobeItemPatch` doesn't need, since it stays hex-only
         *     (research.md §4/§ "API-facing shapes"). `category` covers both the
         *     read view's "Category" (group) and "Group" (specific type) rows — both
         *     write the same underlying column, see research.md §4.
         */
        ClosetItemEditRequest: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Fabric */
            fabric?: string | null;
            /** Colors Text */
            colors_text?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ClosetItemView
         * @description `WardrobeItem` plus display-only computed fields the frontend must
         *     never re-derive itself (caught in `/speckit-analyze`): `category_group`
         *     (`categories.group_of`) and `color_names` (`colors.nearest_names`) are
         *     both backend-only Python logic. Route-local, not part of the AI-pipeline
         *     contract — matches `whoami.py`'s existing pattern of defining its own
         *     response model beside the route.
         *
         *     `photo_url` (feature 006) is a short-lived signed URL minted at read
         *     time, never stored (data-model.md §5) — `None` when the item has no
         *     photo. Populated by the route, not this classmethod, since signing
         *     needs the caller's own access token, which this model has no access to
         *     and shouldn't (`ports.ClosetRepository` stays untouched).
         *
         *     `isolated_photo_url` (feature 018) is the same idea applied to
         *     `isolated_photo_path` — signed at read time, `None` when the item has
         *     no isolated image (a normal, saveable outcome, not an error).
         */
        ClosetItemView: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Colors */
            colors?: string[];
            /**
             * Formality
             * @enum {string}
             */
            formality: "casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie";
            /** Warmth */
            warmth: number;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter")[];
            /** Fabric */
            fabric?: string | null;
            /** Source */
            source?: ("catalog" | "upload") | null;
            /** Pattern */
            pattern?: string | null;
            /** Fit */
            fit?: string | null;
            /** Photo Path */
            photo_path?: string | null;
            /** Isolated Photo Path */
            isolated_photo_path?: string | null;
            /** Photo Background Color */
            photo_background_color?: string | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Favorite
             * @default false
             */
            favorite: boolean;
            /**
             * Category Group
             * @enum {string}
             */
            category_group: "top" | "bottom" | "full_body" | "outerwear" | "footwear" | "accessory";
            /** Color Names */
            color_names: string[];
            /** Photo Url */
            photo_url?: string | null;
            /** Isolated Photo Url */
            isolated_photo_url?: string | null;
        };
        /** ClosetItemsResponse */
        ClosetItemsResponse: {
            /** Items */
            items: components["schemas"]["ClosetItemView"][];
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
        };
        /** ConnectFinishRequest */
        ConnectFinishRequest: {
            /** Code */
            code: string;
            /** State */
            state: string;
        };
        /** ConnectionResponse */
        ConnectionResponse: {
            /** Connected */
            connected: boolean;
            /** Connected At */
            connected_at: string | null;
        };
        /**
         * CreateWardrobeItemFromUploadRequest
         * @description Body of a wardrobe-item-from-upload request — the user-confirmed
         *     (possibly corrected) attributes.
         *
         *     `formality`/`warmth`/`season` are REQUIRED, reversing design-decisions
         *     §23.3. They were briefly optional, on the reasoning that the design's
         *     six-field review card must not be blocked by anything outside it — but
         *     the frontend then simply never sent them, and this route substituted
         *     defaults. Every item added by photo landed as
         *     `formality='casual', warmth=3, season=[all four]` regardless of what
         *     the VLM had actually detected, which is worse than either a blocked
         *     save or an honest null: it is fabricated data, indistinguishable from
         *     a real reading, feeding a styling pipeline that reasons over exactly
         *     these fields. The review card now carries all eight extracted
         *     attributes (design-decisions.md §30), so requiring them here is what
         *     makes "the scan's findings are what gets stored" enforceable rather
         *     than merely intended — the legacy app's own SC-003 guarantee.
         *
         *     `fabric`/`pattern`/`fit` stay optional: the database allows NULL for
         *     them, so an honest "not detected, not supplied" is representable and
         *     no default has to be invented.
         *
         *     `name`/`notes` are on the review card too but are never scan-filled —
         *     `vision.py`'s `_EXTRACTION_SCHEMA` has no such fields (the VLM prompt
         *     only asks for garment attributes, not a user-facing label), so these
         *     two start blank on every review card and are purely user-typed,
         *     matching `WardrobeItem`'s own existing optionality for both.
         */
        CreateWardrobeItemFromUploadRequest: {
            /** Photo Path */
            photo_path: string;
            /** Isolated Photo Path */
            isolated_photo_path?: string | null;
            /** Category */
            category: string;
            /** Colors */
            colors: string[];
            /**
             * Formality
             * @enum {string}
             */
            formality: "casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie";
            /** Warmth */
            warmth: number;
            /** Season */
            season: ("spring" | "summer" | "autumn" | "winter")[];
            /** Fabric */
            fabric?: string | null;
            /** Pattern */
            pattern?: string | null;
            /** Fit */
            fit?: string | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Photo Background Color */
            photo_background_color?: string | null;
        };
        /**
         * DimensionScoreView
         * @description One bar in Outfit detail's Match breakdown (design-system.md §
         *     Scores). `value` is transmitted for the frontend to compute a bar's
         *     fill width — it is never rendered as visible text on any screen
         *     (design-decisions.md §38's explicit transmit-vs-render distinction).
         */
        DimensionScoreView: {
            /** Dimension */
            dimension: string;
            /** Value */
            value: number;
        };
        /** EventsResponse */
        EventsResponse: {
            /** Events */
            events: components["schemas"]["CalendarEventView"][];
        };
        /**
         * ExtractedAttributes
         * @description Draft output of one VLM extraction call over a single item photo
         *     (vision.py). Every field optional — extraction failing on any/all of
         *     them must not block adding the item; the user fills in whatever's
         *     missing.
         */
        ExtractedAttributes: {
            /** Category */
            category?: string | null;
            /** Colors */
            colors?: string[] | null;
            /** Fabric */
            fabric?: string | null;
            /** Warmth */
            warmth?: number | null;
            /** Formality */
            formality?: ("casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie") | null;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter")[] | null;
            /** Pattern */
            pattern?: string | null;
            /** Fit */
            fit?: string | null;
            /** Background Color */
            background_color?: string | null;
        };
        /** FavoriteToggleResponse */
        FavoriteToggleResponse: {
            /** Favorite */
            favorite: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NotificationsUpdate */
        NotificationsUpdate: {
            /** Notifications Enabled */
            notifications_enabled: boolean;
        };
        /**
         * OutfitDetailResponse
         * @description Outfit detail (design-system.md § Outfit detail) — feature 010.
         */
        OutfitDetailResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Occasion */
            occasion: string;
            /** Items */
            items: components["schemas"]["RecommendItemView"][];
            /** Rationale Text */
            rationale_text: string;
            /** Rationale With Citations */
            rationale_with_citations: string;
            /** Citations */
            citations: components["schemas"]["CitedRuleView"][];
            /** Dimension Scores */
            dimension_scores: components["schemas"]["DimensionScoreView"][];
            /**
             * Match Label
             * @enum {string}
             */
            match_label: "great" | "good" | "might_work";
            /** Favorite */
            favorite: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OutfitSummary
         * @description The Outfits gallery card (design-system.md § Outfits (gallery)) —
         *     feature 010. `item_thumbnails` is capped at 4 (the card's own real-
         *     thumbnail limit); `item_count` lets the frontend compute the "+N"
         *     overflow chip without a second request.
         */
        OutfitSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Match Label
             * @enum {string}
             */
            match_label: "great" | "good" | "might_work";
            /** Favorite */
            favorite: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Item Thumbnails */
            item_thumbnails: components["schemas"]["RecommendItemView"][];
            /** Item Count */
            item_count: number;
        };
        /** OutfitSummaryListResponse */
        OutfitSummaryListResponse: {
            /** Outfits */
            outfits: components["schemas"]["OutfitSummary"][];
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
        };
        /**
         * PhotoExtractionListView
         * @description Same shape `PhotoExtractionListResponse` describes (`drafts` +
         *     `truncated`), with `drafts` narrowed to `PhotoExtractionView` — a fresh
         *     model rather than a subclass overriding `PhotoExtractionListResponse.
         *     drafts`'s type, which mypy rejects (`list` is invariant). Matches
         *     `ClosetItemsResponse`'s own fresh-model pattern for the same "list of
         *     route-local views" shape.
         */
        PhotoExtractionListView: {
            /** Drafts */
            drafts: components["schemas"]["PhotoExtractionView"][];
            /** Truncated */
            truncated: boolean;
        };
        /**
         * PhotoExtractionView
         * @description `PhotoExtractionResponse` plus two display-only computed fields,
         *     same pattern as `ClosetItemView` over `WardrobeItem`: the review
         *     card's Color field pre-fills with a NAME (`colors.nearest_names`), not
         *     the raw hex `extracted.colors` carries, and `isolated_photo_url` is a
         *     signed URL (feature 018) minted for `isolated_photo_path`, same idea
         *     as `ClosetItemView.photo_url` over `WardrobeItem.photo_path` — both
         *     computed here, route-local, so `PhotoExtractionResponse`/
         *     `ExtractedAttributes` (feature 007's AI-layer contract) stay untouched
         *     (design-decisions.md §23.4, research.md §5).
         */
        PhotoExtractionView: {
            /** Photo Path */
            photo_path: string;
            extracted: components["schemas"]["ExtractedAttributes"];
            /** Extraction Ok */
            extraction_ok: boolean;
            region: components["schemas"]["BoundingBox"];
            /** Isolated Photo Path */
            isolated_photo_path?: string | null;
            /** Color Names */
            color_names: string[];
            /** Isolated Photo Url */
            isolated_photo_url?: string | null;
        };
        /** PickedEventRequest */
        PickedEventRequest: {
            /** Google Event Id */
            google_event_id: string;
            /** Title */
            title: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Location */
            location: string | null;
        };
        /** PickedEventView */
        PickedEventView: {
            /** Picked */
            picked: boolean;
            event: components["schemas"]["CalendarEventView"] | null;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Style Tags */
            style_tags?: string[];
            /** Colour Tags */
            colour_tags?: string[];
            /** Brands To Avoid */
            brands_to_avoid?: string[];
            /** Body Shape */
            body_shape?: string | null;
            /** Gender */
            gender?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Height */
            height?: string | null;
            /** Top Size */
            top_size?: string | null;
            /** Bottom Size */
            bottom_size?: string | null;
            /** Shoe Size */
            shoe_size?: string | null;
            /**
             * Notifications Enabled
             * @default true
             */
            notifications_enabled: boolean;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Ready */
            ready: boolean;
            /** Sparse */
            sparse: boolean;
            /** Missing */
            missing: string[];
        };
        /**
         * RecommendItemView
         * @description A route-local view of `WardrobeItem`, deliberately not imported from
         *     `closet.py` — every route in this codebase defines its own response
         *     model beside itself (`closet.py`'s own `ClosetItemView` docstring notes
         *     it does the same relative to `whoami.py`), so this mirrors that shape
         *     rather than coupling two route modules together.
         */
        RecommendItemView: {
            /** Id */
            id: string;
            /** Name */
            name: string | null;
            /** Category */
            category: string;
            /**
             * Category Group
             * @enum {string}
             */
            category_group: "top" | "bottom" | "full_body" | "outerwear" | "footwear" | "accessory";
            /** Colors */
            colors: string[];
            /** Color Names */
            color_names: string[];
            /** Photo Url */
            photo_url: string | null;
            /** Photo Background Color */
            photo_background_color: string | null;
        };
        /** RenameOutfitRequest */
        RenameOutfitRequest: {
            /** Title */
            title: string;
        };
        /** RenamedOutfitResponse */
        RenamedOutfitResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /** SavedOutfitResponse */
        SavedOutfitResponse: {
            /** Id */
            id: string;
            /** Favorite */
            favorite: boolean;
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Message */
            message: string;
            /** Thread Id */
            thread_id?: string | null;
        };
        /** SendMessageResponse */
        SendMessageResponse: {
            /** Thread Id */
            thread_id: string;
            /** Reply Text */
            reply_text: string | null;
            /** Wrap Up Text */
            wrap_up_text: string;
            /** Outfits */
            outfits: components["schemas"]["StylingOutfit"][];
        };
        /** SendTurnRequest */
        SendTurnRequest: {
            /** Message */
            message: string;
            /** Thread Id */
            thread_id?: string | null;
        };
        /**
         * SendTurnResponse
         * @description feature 016, contracts/recommend-turns.md — this turn's own extraction only, not the
         *     accumulated set (that lives server-side in the pipeline's checkpointer, design-decisions.md
         *     §47, and is never round-tripped to the client).
         */
        SendTurnResponse: {
            /** Thread Id */
            thread_id: string;
            /** Reply Text */
            reply_text: string;
            /** Occasion */
            occasion: string | null;
            /** Formality */
            formality: string | null;
            /** Mood */
            mood: string | null;
            /** Temp C */
            temp_c: number | null;
            /** Location */
            location: string | null;
        };
        /**
         * SessionDetailResponse
         * @description Session detail (design-system.md § Chat history / Session detail) —
         *     feature 011. `id` is what "Continue conversation" resumes with (it IS
         *     the thread_id, §44).
         */
        SessionDetailResponse: {
            /** Id */
            id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Outfit Count */
            outfit_count: number;
            /** Messages */
            messages: components["schemas"]["SessionMessageView"][];
        };
        /**
         * SessionMessageOutfitView
         * @description design-decisions.md §46: the archived view's citation Badges render
         *     from the outfit's own already-grounded `rationale_with_citations`/
         *     `citations` — deliberately no `items`/thumbnails and no separate
         *     rule-list-only fields beyond `citations` itself.
         */
        SessionMessageOutfitView: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Rationale With Citations */
            rationale_with_citations: string;
            /** Citations */
            citations: components["schemas"]["CitedRuleView"][];
        };
        /** SessionMessageView */
        SessionMessageView: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Text */
            text: string;
            /** Outfits */
            outfits: components["schemas"]["SessionMessageOutfitView"][];
        };
        /**
         * SessionSummary
         * @description One row of Chat history's list (design-system.md § Chat history —
         *     feature 011). `outfit_count` is always present and `>= 0`; the
         *     frontend renders the third preview line only when it is `> 0`
         *     (design-decisions.md §45 — never a fabricated count for a session with
         *     none).
         */
        SessionSummary: {
            /** Id */
            id: string;
            /** Preview */
            preview: string | null;
            /** Message Count */
            message_count: number;
            /** Outfit Count */
            outfit_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SessionSummaryListResponse */
        SessionSummaryListResponse: {
            /** Sessions */
            sessions: components["schemas"]["SessionSummary"][];
        };
        /** StylePreferencesUpdate */
        StylePreferencesUpdate: {
            /** Style Tags */
            style_tags: string[];
            /** Colour Tags */
            colour_tags: string[];
            /** Brands To Avoid */
            brands_to_avoid: string[];
        };
        /** StylingOutfit */
        StylingOutfit: {
            /** Id */
            id: string;
            /** Occasion */
            occasion: string;
            /** Rationale Text */
            rationale_text: string;
            /** Items */
            items: components["schemas"]["RecommendItemView"][];
            /**
             * Match Label
             * @enum {string}
             */
            match_label: "great" | "good" | "might_work";
            /** Meta Line */
            meta_line: string;
            /** Favorite */
            favorite: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhoamiResponse */
        WhoamiResponse: {
            /** User Id */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    whoami_api_v1_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiResponse"];
                };
            };
        };
    };
    list_closet_items_api_v1_closet_items_get: {
        parameters: {
            query?: {
                category?: ("top" | "bottom" | "outerwear" | "footwear" | "accessory") | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosetItemsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_closet_item_api_v1_closet_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosetItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_closet_item_api_v1_closet_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_closet_item_api_v1_closet_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClosetItemEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosetItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_closet_item_favorite_api_v1_closet_items__item_id__favorite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteToggleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_closet_item_worn_api_v1_closet_items__item_id__wear_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_closet_item_api_v1_closet_items_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_closet_item_api_v1_closet_items_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoExtractionListView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_closet_item_from_upload_api_v1_closet_items_from_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWardrobeItemFromUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosetItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    update_style_preferences_api_v1_profile_style_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StylePreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_body_size_api_v1_profile_body_size_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodySizeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_notifications_api_v1_profile_notifications_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_api_v1_calendar_connection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"];
                };
            };
        };
    };
    start_connect_api_v1_calendar_connect_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizeUrlResponse"];
                };
            };
        };
    };
    finish_connect_api_v1_calendar_connect_finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectFinishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_api_v1_calendar_disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"];
                };
            };
        };
    };
    list_events_api_v1_calendar_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
        };
    };
    get_picked_event_api_v1_calendar_picked_event_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickedEventView"];
                };
            };
        };
    };
    set_picked_event_api_v1_calendar_picked_event_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickedEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickedEventView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_taxonomy_api_v1_taxonomy_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    get_readiness_api_v1_recommend_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    send_turn_api_v1_recommend_turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_v1_recommend_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_recommend_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryListResponse"];
                };
            };
        };
    };
    get_session_api_v1_recommend_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outfits_api_v1_recommend_outfits_get: {
        parameters: {
            query?: {
                sort?: "date" | "favorite" | "most_worn";
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutfitSummaryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outfit_api_v1_recommend_outfits__outfit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outfit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutfitDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_outfit_api_v1_recommend_outfits__outfit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outfit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_outfit_api_v1_recommend_outfits__outfit_id__title_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outfit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameOutfitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenamedOutfitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_outfit_worn_api_v1_recommend_outfits__outfit_id__wear_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outfit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_outfit_favorite_api_v1_recommend_outfits__outfit_id__favorite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outfit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedOutfitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
