/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_api_v1_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/closet/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Closet Items */
        get: operations["list_closet_items_api_v1_closet_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/closet/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Closet Item */
        get: operations["get_closet_item_api_v1_closet_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClosetItemView
         * @description `WardrobeItem` plus display-only computed fields the frontend must
         *     never re-derive itself (caught in `/speckit-analyze`): `category_group`
         *     (`categories.group_of`) and `color_names` (`colors.nearest_names`) are
         *     both backend-only Python logic. Route-local, not part of the AI-pipeline
         *     contract — matches `whoami.py`'s existing pattern of defining its own
         *     response model beside the route.
         */
        ClosetItemView: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Colors */
            colors?: string[];
            /**
             * Formality
             * @enum {string}
             */
            formality: "casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie";
            /** Warmth */
            warmth: number;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter")[];
            /** Fabric */
            fabric?: string | null;
            /** Source */
            source?: ("catalog" | "upload") | null;
            /** Pattern */
            pattern?: string | null;
            /** Fit */
            fit?: string | null;
            /** Photo Path */
            photo_path?: string | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Category Group
             * @enum {string}
             */
            category_group: "top" | "bottom" | "full_body" | "outerwear" | "footwear" | "accessory";
            /** Color Names */
            color_names: string[];
        };
        /** ClosetItemsResponse */
        ClosetItemsResponse: {
            /** Items */
            items: components["schemas"]["ClosetItemView"][];
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhoamiResponse */
        WhoamiResponse: {
            /** User Id */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    whoami_api_v1_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiResponse"];
                };
            };
        };
    };
    list_closet_items_api_v1_closet_items_get: {
        parameters: {
            query?: {
                category?: ("top" | "bottom" | "outerwear" | "footwear" | "accessory") | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosetItemsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_closet_item_api_v1_closet_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosetItemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
