/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Endpoint
         * @description Supersedes /recommend (contracts/suggest.md). Same auth model — the
         *     requester's identity always comes from the verified JWT `sub`, never the
         *     body. SSE: an `outfit` event per ranked outfit, then a `done` event
         *     carrying the full response shape (a client that only reads `done` gets
         *     the exact non-streaming payload). `response_model` is for OpenAPI docs
         *     only — returning a Response subclass directly makes FastAPI skip
         *     response_model serialization, but it's still what generates the
         *     SuggestResult/ScoredOutfit/DimensionScore schemas the frontend needs
         *     (T036b) since a raw StreamingResponse alone wouldn't.
         */
        post: operations["suggest_endpoint_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wardrobe/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Wardrobe Items */
        get: operations["list_wardrobe_items_wardrobe_items_get"];
        put?: never;
        /** Add Wardrobe Item */
        post: operations["add_wardrobe_item_wardrobe_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Catalog Items */
        get: operations["list_catalog_items_catalog_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wardrobe/items/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Wardrobe Items Bulk */
        post: operations["add_wardrobe_items_bulk_wardrobe_items_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wardrobe/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Wardrobe Item */
        delete: operations["delete_wardrobe_item_wardrobe_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Wardrobe Item */
        patch: operations["update_wardrobe_item_wardrobe_items__item_id__patch"];
        trace?: never;
    };
    "/wardrobe/items/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Wardrobe Item
         * @description Draft extraction only — nothing is persisted to wardrobe_items here
         *     (US2). A photo that can't be confidently interpreted is still a 200 with
         *     extraction_ok=False, never a 5xx (FR-006).
         */
        post: operations["extract_wardrobe_item_wardrobe_items_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wardrobe/items/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Wardrobe Item
         * @description Persists a wardrobe item from user-confirmed (possibly corrected)
         *     attributes -- source='upload', parallel to, not replacing, the
         *     catalog-based POST /wardrobe/items (US2).
         */
        post: operations["upload_wardrobe_item_wardrobe_items_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddWardrobeItemRequest */
        AddWardrobeItemRequest: {
            /**
             * Catalog Item Id
             * Format: uuid
             */
            catalog_item_id: string;
        };
        /** AddWardrobeItemsBulkRequest */
        AddWardrobeItemsBulkRequest: {
            /** Catalog Item Ids */
            catalog_item_ids: string[];
        };
        /** Body_extract_wardrobe_item_wardrobe_items_extract_post */
        Body_extract_wardrobe_item_wardrobe_items_extract_post: {
            /** Photo */
            photo: string;
        };
        /** CitedSource */
        CitedSource: {
            /** Rule Id */
            rule_id: string;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /**
             * Layer
             * @enum {string}
             */
            layer: "L1" | "L2" | "L3" | "L4";
        };
        /**
         * Context
         * @description Normalized request context (pipeline stage 1 output).
         */
        Context: {
            /** Occasion */
            occasion: string;
            /**
             * Formality
             * @enum {string}
             */
            formality: "casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie";
            /** Mood */
            mood?: string | null;
            /** Temp C */
            temp_c?: number | null;
            /** Condition */
            condition?: string | null;
            /** Temp Band */
            temp_band?: ("freezing" | "cold" | "cool" | "mild" | "warm" | "hot") | null;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter") | null;
            /** Wardrobe */
            wardrobe?: components["schemas"]["WardrobeItem"][];
            /** User Id */
            user_id?: string | null;
        };
        /**
         * CreateWardrobeItemFromUploadRequest
         * @description Body of POST /wardrobe/items/upload — the user-confirmed (possibly
         *     corrected) attributes. fabric/pattern/fit are required HERE ONLY: SC-003
         *     requires 100% of items saved through the photo flow to have every
         *     attribute populated, none blank. WardrobeItem/WardrobeItemPatch (the
         *     correction path) keep all three optional, unchanged.
         */
        CreateWardrobeItemFromUploadRequest: {
            /** Photo Path */
            photo_path: string;
            /** Category */
            category: string;
            /** Colors */
            colors: string[];
            /**
             * Formality
             * @enum {string}
             */
            formality: "casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie";
            /** Warmth */
            warmth: number;
            /** Season */
            season: ("spring" | "summer" | "autumn" | "winter")[];
            /** Fabric */
            fabric: string;
            /** Pattern */
            pattern: string;
            /** Fit */
            fit: string;
        };
        /**
         * DimensionScore
         * @description One deterministic scorer's output for one outfit (data-model.md).
         */
        DimensionScore: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "color_harmony" | "formality_coherence" | "weather_fitness" | "silhouette_balance";
            /** Value */
            value: number;
            /** Reason */
            reason: string;
        };
        /**
         * ExtractedAttributes
         * @description Draft output of one VLM extraction call over a single item photo.
         *     Every field optional — extraction failing on any/all of them must not
         *     block adding the item (FR-006); the user fills in whatever's missing.
         */
        ExtractedAttributes: {
            /** Category */
            category?: string | null;
            /** Colors */
            colors?: string[] | null;
            /** Fabric */
            fabric?: string | null;
            /** Warmth */
            warmth?: number | null;
            /** Formality */
            formality?: ("casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie") | null;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter")[] | null;
            /** Pattern */
            pattern?: string | null;
            /** Fit */
            fit?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PhotoExtractionResponse
         * @description What POST /wardrobe/items/extract returns — an unsaved draft.
         */
        PhotoExtractionResponse: {
            /** Photo Path */
            photo_path: string;
            extracted: components["schemas"]["ExtractedAttributes"];
            /** Extraction Ok */
            extraction_ok: boolean;
        };
        /** Rationale */
        Rationale: {
            /** Text */
            text: string;
            /** Cites */
            cites?: string[];
        };
        /**
         * ScoredOutfit
         * @description An `Outfit` extended with per-dimension scores and a combined rank
         *     score (data-model.md). `scores` always carries exactly one entry per
         *     `SCORE_DIMENSIONS` value (FR-008).
         */
        ScoredOutfit: {
            /** Items */
            items: string[];
            /** Rationale */
            rationale: components["schemas"]["Rationale"][];
            /** Scores */
            scores: components["schemas"]["DimensionScore"][];
            /** Rank Score */
            rank_score: number;
        };
        /**
         * SuggestRequest
         * @description Body of POST /suggest (contracts/suggest.md). No `user_id` field —
         *     same fix as RecommendRequest post-Phase-1: identity always comes from
         *     the verified JWT `sub` (FR-001).
         */
        SuggestRequest: {
            /** Occasion */
            occasion: string;
            /** Mood */
            mood?: string | null;
            /** Formality */
            formality?: ("casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie") | null;
            /** Location */
            location?: string | null;
            /** Temp C */
            temp_c?: number | null;
            /**
             * Strategy
             * @default advanced
             */
            strategy: string;
            /** Thread Id */
            thread_id?: string | null;
        };
        /**
         * SuggestResult
         * @description What POST /suggest's `result` field carries (contracts/suggest.md) —
         *     OutfitResult's shape, but with ScoredOutfit entries. A separate type
         *     from OutfitResult (not a field-type change on it) because /recommend is
         *     still live and its old code path can't populate scores; data-model.md
         *     calls for OutfitResult.outfits to become list[ScoredOutfit] only once
         *     /recommend is retired (tasks.md T037a), at which point this type merges
         *     into OutfitResult rather than the two coexisting indefinitely.
         */
        SuggestResult: {
            /** Outfits */
            outfits: components["schemas"]["ScoredOutfit"][];
            /** Sources */
            sources?: components["schemas"]["CitedSource"][];
            context?: components["schemas"]["Context"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WardrobeItem
         * @description A single owned garment. Wardrobe capture is out of scope this phase;
         *     this is the shape the capture flow must eventually emit.
         *
         *     `colors` are hex — the source of truth (see colors.py). Human-readable
         *     names are derived on demand via colors.nearest_names(), never stored, so
         *     name and hex can never drift out of sync.
         */
        WardrobeItem: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Colors */
            colors?: string[];
            /**
             * Formality
             * @enum {string}
             */
            formality: "casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie";
            /** Warmth */
            warmth: number;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter")[];
            /** Fabric */
            fabric?: string | null;
            /** Source */
            source?: ("catalog" | "upload") | null;
            /** Pattern */
            pattern?: string | null;
            /** Fit */
            fit?: string | null;
        };
        /**
         * WardrobeItemPatch
         * @description A partial correction to an owned WardrobeItem (US3). Every field is
         *     optional -- only fields present in the request are applied, matching
         *     PATCH semantics. Reuses the same field-level validation as WardrobeItem
         *     so an invalid value is rejected with a 422 before it ever reaches the DB
         *     (FR-007), while `category` stays open-ended (its slot/bucket is derived
         *     on read via categories.group_of(), never itself validated here).
         */
        WardrobeItemPatch: {
            /** Category */
            category?: string | null;
            /** Colors */
            colors?: string[] | null;
            /** Formality */
            formality?: ("casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie") | null;
            /** Warmth */
            warmth?: number | null;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter")[] | null;
            /** Fabric */
            fabric?: string | null;
            /** Pattern */
            pattern?: string | null;
            /** Fit */
            fit?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    suggest_endpoint_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wardrobe_items_wardrobe_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"][];
                };
            };
        };
    };
    add_wardrobe_item_wardrobe_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWardrobeItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_catalog_items_catalog_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"][];
                };
            };
        };
    };
    add_wardrobe_items_bulk_wardrobe_items_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWardrobeItemsBulkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_wardrobe_item_wardrobe_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_wardrobe_item_wardrobe_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WardrobeItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_wardrobe_item_wardrobe_items_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_wardrobe_item_wardrobe_items_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_wardrobe_item_wardrobe_items_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWardrobeItemFromUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
