/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description FR-012 (Feature 005, a `/speckit.analyze` finding against the spec's
         *     own Edge Case): reports failure when the database or vector store is
         *     unreachable, not merely when the process itself is running.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Endpoint
         * @description Supersedes /recommend (contracts/suggest.md). Same auth model — the
         *     requester's identity always comes from the verified JWT `sub`, never the
         *     body. SSE: an `outfit` event per ranked outfit, then a `done` event
         *     carrying the full response shape (a client that only reads `done` gets
         *     the exact non-streaming payload). `response_model` is for OpenAPI docs
         *     only — returning a Response subclass directly makes FastAPI skip
         *     response_model serialization, but it's still what generates the
         *     SuggestResult/ScoredOutfit/DimensionScore schemas the frontend needs
         *     (T036b) since a raw StreamingResponse alone wouldn't.
         *
         *     Feature 005 US3/FR-006/007: a fresh (non-continuing) request — no
         *     incoming `thread_id` — is eligible for the per-user Redis cache
         *     (`pipeline/cache.py`). A refinement turn (`thread_id` supplied,
         *     continuing a conversation the checkpointer already has state for)
         *     always runs the graph — refinements are inherently stateful and aren't
         *     idempotent the way a first turn is (research.md §2). The wardrobe is
         *     loaded once here and passed through to the graph either way (`wardrobe=`
         *     override on `GraphState`), so caching doesn't cost a second DB fetch.
         *
         *     A cache hit still seeds the checkpointer (`graph.update_state`) with the
         *     turn's `ctx`/`original_context`/`last_result` before returning — found
         *     necessary during implementation: a hit's `thread_id` is otherwise never
         *     passed to `graph.invoke`, so the checkpointer would have no state for it,
         *     and a later refinement turn continuing that `thread_id` would wrongly be
         *     treated as a brand-new conversation (`parse_request` only detects a
         *     continuation via `original_context` already being checkpointed).
         */
        post: operations["suggest_endpoint_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wardrobe/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Wardrobe Items */
        get: operations["list_wardrobe_items_wardrobe_items_get"];
        put?: never;
        /** Add Wardrobe Item */
        post: operations["add_wardrobe_item_wardrobe_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Catalog Items */
        get: operations["list_catalog_items_catalog_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wardrobe/items/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Wardrobe Items Bulk */
        post: operations["add_wardrobe_items_bulk_wardrobe_items_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wardrobe/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Wardrobe Item */
        delete: operations["delete_wardrobe_item_wardrobe_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Wardrobe Item */
        patch: operations["update_wardrobe_item_wardrobe_items__item_id__patch"];
        trace?: never;
    };
    "/wardrobe/items/{item_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace Wardrobe Item Photo
         * @description Replaces an already-saved item's photo (Feature 008 US4). Uploads via
         *     the same storage.upload_wardrobe_photo extract_wardrobe_item already
         *     uses, but deliberately never calls vision.extract_attributes_from_image
         *     -- a photo swap isn't a re-classification (FR-014), so the item's other
         *     attributes are untouched. Composes the existing update_wardrobe_item for
         *     ownership enforcement (404 on a mismatched/unknown item_id), same as
         *     every other per-item wardrobe operation.
         */
        post: operations["replace_wardrobe_item_photo_wardrobe_items__item_id__photo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wardrobe/items/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Wardrobe Item
         * @description Draft extraction only — nothing is persisted to wardrobe_items here
         *     (US2). A photo that can't be confidently interpreted is still a 200 with
         *     extraction_ok=False, never a 5xx (FR-006).
         */
        post: operations["extract_wardrobe_item_wardrobe_items_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wardrobe/items/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Wardrobe Item
         * @description Persists a wardrobe item from user-confirmed (possibly corrected)
         *     attributes -- source='upload', parallel to, not replacing, the
         *     catalog-based POST /wardrobe/items (US2).
         */
        post: operations["upload_wardrobe_item_wardrobe_items_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Feedback
         * @description Records or replaces a reaction to a specific outfit (US1). item_ids
         *     are resolved against the caller's own wardrobe -- an id that doesn't
         *     exist or belongs to someone else is a 404, never silently accepted.
         */
        post: operations["submit_feedback_preferences_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Preferences
         * @description A plain-language summary of what's been learned (US3). has_feedback
         *     distinguishes "no feedback at all" from "feedback exists, no signal has
         *     crossed threshold yet" -- both have signals=[], only the former is False.
         */
        get: operations["get_preferences_preferences_get"];
        put?: never;
        post?: never;
        /**
         * Clear Preferences
         * @description Clears the entire derived profile in one action (US4) -- dismisses
         *     every signal currently present, reusing the exact same per-signal
         *     mechanism as remove_preference_signal rather than a separate code path
         *     (research.md #3).
         */
        delete: operations["clear_preferences_preferences_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences/signals/{signal_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Preference Signal
         * @description Removes one derived signal without affecting the rest of the profile
         *     (US4). Idempotent -- dismissing an already-absent signal is a no-op,
         *     not a 404 (contracts/preferences.md).
         */
        delete: operations["remove_preference_signal_preferences_signals__signal_key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddWardrobeItemRequest */
        AddWardrobeItemRequest: {
            /**
             * Catalog Item Id
             * Format: uuid
             */
            catalog_item_id: string;
        };
        /** AddWardrobeItemsBulkRequest */
        AddWardrobeItemsBulkRequest: {
            /** Catalog Item Ids */
            catalog_item_ids: string[];
        };
        /** Body_extract_wardrobe_item_wardrobe_items_extract_post */
        Body_extract_wardrobe_item_wardrobe_items_extract_post: {
            /** Photo */
            photo: string;
        };
        /** Body_replace_wardrobe_item_photo_wardrobe_items__item_id__photo_post */
        Body_replace_wardrobe_item_photo_wardrobe_items__item_id__photo_post: {
            /** Photo */
            photo: string;
        };
        /** CitedSource */
        CitedSource: {
            /** Rule Id */
            rule_id: string;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /**
             * Layer
             * @enum {string}
             */
            layer: "L1" | "L2" | "L3" | "L4";
        };
        /**
         * Context
         * @description Normalized request context (pipeline stage 1 output).
         */
        Context: {
            /** Occasion */
            occasion: string;
            /**
             * Formality
             * @enum {string}
             */
            formality: "casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie";
            /** Mood */
            mood?: string | null;
            /** Temp C */
            temp_c?: number | null;
            /** Condition */
            condition?: string | null;
            /** Temp Band */
            temp_band?: ("freezing" | "cold" | "cool" | "mild" | "warm" | "hot") | null;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter") | null;
            /** Wardrobe */
            wardrobe?: components["schemas"]["WardrobeItem"][];
            /** User Id */
            user_id?: string | null;
        };
        /**
         * CreateWardrobeItemFromUploadRequest
         * @description Body of POST /wardrobe/items/upload — the user-confirmed (possibly
         *     corrected) attributes. fabric/pattern/fit are required HERE ONLY: SC-003
         *     requires 100% of items saved through the photo flow to have every
         *     attribute populated, none blank. WardrobeItem/WardrobeItemPatch (the
         *     correction path) keep all three optional, unchanged.
         */
        CreateWardrobeItemFromUploadRequest: {
            /** Photo Path */
            photo_path: string;
            /** Category */
            category: string;
            /** Colors */
            colors: string[];
            /**
             * Formality
             * @enum {string}
             */
            formality: "casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie";
            /** Warmth */
            warmth: number;
            /** Season */
            season: ("spring" | "summer" | "autumn" | "winter")[];
            /** Fabric */
            fabric: string;
            /** Pattern */
            pattern: string;
            /** Fit */
            fit: string;
        };
        /**
         * DimensionScore
         * @description One deterministic scorer's output for one outfit (data-model.md).
         */
        DimensionScore: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "color_harmony" | "formality_coherence" | "weather_fitness" | "silhouette_balance";
            /** Value */
            value: number;
            /** Reason */
            reason: string;
        };
        /**
         * ExtractedAttributes
         * @description Draft output of one VLM extraction call over a single item photo.
         *     Every field optional — extraction failing on any/all of them must not
         *     block adding the item (FR-006); the user fills in whatever's missing.
         */
        ExtractedAttributes: {
            /** Category */
            category?: string | null;
            /** Colors */
            colors?: string[] | null;
            /** Fabric */
            fabric?: string | null;
            /** Warmth */
            warmth?: number | null;
            /** Formality */
            formality?: ("casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie") | null;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter")[] | null;
            /** Pattern */
            pattern?: string | null;
            /** Fit */
            fit?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PhotoExtractionResponse
         * @description What POST /wardrobe/items/extract returns — an unsaved draft.
         */
        PhotoExtractionResponse: {
            /** Photo Path */
            photo_path: string;
            extracted: components["schemas"]["ExtractedAttributes"];
            /** Extraction Ok */
            extraction_ok: boolean;
        };
        /**
         * PreferenceProfile
         * @description What GET /preferences returns. has_feedback distinguishes "no
         *     feedback at all" (FR-008's empty state) from "feedback exists but no
         *     signal has crossed threshold yet" (also signals=[], but has_feedback is
         *     True).
         */
        PreferenceProfile: {
            /** Has Feedback */
            has_feedback: boolean;
            /** Signals */
            signals?: components["schemas"]["PreferenceSignal"][];
        };
        /** PreferenceSignal */
        PreferenceSignal: {
            /** Key */
            key: string;
            /** Summary */
            summary: string;
        };
        /** Rationale */
        Rationale: {
            /** Text */
            text: string;
            /** Cites */
            cites?: string[];
        };
        /**
         * ScoredOutfit
         * @description An `Outfit` extended with per-dimension scores and a combined rank
         *     score (data-model.md). `scores` always carries exactly one entry per
         *     `SCORE_DIMENSIONS` value (FR-008).
         */
        ScoredOutfit: {
            /** Items */
            items: string[];
            /** Rationale */
            rationale: components["schemas"]["Rationale"][];
            /** Scores */
            scores: components["schemas"]["DimensionScore"][];
            /** Rank Score */
            rank_score: number;
        };
        /**
         * SubmitFeedbackRequest
         * @description Body of POST /preferences/feedback. item_ids identify the reacted-to
         *     outfit -- resolved server-side against the caller's own wardrobe_items,
         *     never trusted as-is (see crud.record_feedback).
         */
        SubmitFeedbackRequest: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "liked" | "rejected";
            /** Reason */
            reason?: string | null;
            /** Item Ids */
            item_ids: string[];
        };
        /**
         * SuggestRequest
         * @description Body of POST /suggest (contracts/suggest.md). No `user_id` field —
         *     same fix as RecommendRequest post-Phase-1: identity always comes from
         *     the verified JWT `sub` (FR-001).
         *
         *     `approach` (Feature 010, WP2): which selection strategy to run.
         *     `"grounded"` names today's existing default pipeline (LLM assembles
         *     outfits, `generate_outfits`/`score_and_rank`) so its meaning is
         *     explicit rather than implicit-via-absence. Only `"grounded"` (the
         *     default) and `"engine"` are routed anywhere by this feature; the other
         *     values are accepted (matching the full roadmap) but fall through to
         *     the `grounded` branch unchanged, same as omitting the field.
         */
        SuggestRequest: {
            /** Occasion */
            occasion: string;
            /** Mood */
            mood?: string | null;
            /** Formality */
            formality?: ("casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie") | null;
            /** Location */
            location?: string | null;
            /** Temp C */
            temp_c?: number | null;
            /**
             * Strategy
             * @default advanced
             */
            strategy: string;
            /** Thread Id */
            thread_id?: string | null;
            /**
             * Approach
             * @default grounded
             * @enum {string}
             */
            approach: "direct" | "grounded" | "engine" | "agentic" | "compare";
        };
        /**
         * SuggestResult
         * @description What POST /suggest's `result` field carries (contracts/suggest.md) —
         *     OutfitResult's shape, but with ScoredOutfit entries. A separate type
         *     from OutfitResult (not a field-type change on it) since OutfitResult is
         *     kept as `pipeline.cite.build_result`'s internal return shape (see its
         *     docstring above) rather than merged away.
         */
        SuggestResult: {
            /** Outfits */
            outfits: components["schemas"]["ScoredOutfit"][];
            /** Sources */
            sources?: components["schemas"]["CitedSource"][];
            context?: components["schemas"]["Context"] | null;
        };
        /**
         * SuggestionFeedback
         * @description What POST /preferences/feedback returns.
         */
        SuggestionFeedback: {
            /** Id */
            id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "liked" | "rejected";
            /** Reason */
            reason?: string | null;
            /** Item Ids */
            item_ids: string[];
            /** Created At */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WardrobeItem
         * @description A single owned garment. Wardrobe capture is out of scope this phase;
         *     this is the shape the capture flow must eventually emit.
         *
         *     `colors` are hex — the source of truth (see colors.py). Human-readable
         *     names are derived on demand via colors.nearest_names(), never stored, so
         *     name and hex can never drift out of sync.
         */
        WardrobeItem: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Colors */
            colors?: string[];
            /**
             * Formality
             * @enum {string}
             */
            formality: "casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie";
            /** Warmth */
            warmth: number;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter")[];
            /** Fabric */
            fabric?: string | null;
            /** Source */
            source?: ("catalog" | "upload") | null;
            /** Pattern */
            pattern?: string | null;
            /** Fit */
            fit?: string | null;
            /** Photo Path */
            photo_path?: string | null;
        };
        /**
         * WardrobeItemPatch
         * @description A partial correction to an owned WardrobeItem (US3). Every field is
         *     optional -- only fields present in the request are applied, matching
         *     PATCH semantics. Reuses the same field-level validation as WardrobeItem
         *     so an invalid value is rejected with a 422 before it ever reaches the DB
         *     (FR-007), while `category` stays open-ended (its slot/bucket is derived
         *     on read via categories.group_of(), never itself validated here).
         */
        WardrobeItemPatch: {
            /** Category */
            category?: string | null;
            /** Colors */
            colors?: string[] | null;
            /** Formality */
            formality?: ("casual" | "smart_casual" | "business_casual" | "semi_formal" | "formal" | "black_tie") | null;
            /** Warmth */
            warmth?: number | null;
            /** Season */
            season?: ("spring" | "summer" | "autumn" | "winter")[] | null;
            /** Fabric */
            fabric?: string | null;
            /** Pattern */
            pattern?: string | null;
            /** Fit */
            fit?: string | null;
            /** Photo Path */
            photo_path?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    suggest_endpoint_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wardrobe_items_wardrobe_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"][];
                };
            };
        };
    };
    add_wardrobe_item_wardrobe_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWardrobeItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_catalog_items_catalog_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"][];
                };
            };
        };
    };
    add_wardrobe_items_bulk_wardrobe_items_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWardrobeItemsBulkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_wardrobe_item_wardrobe_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_wardrobe_item_wardrobe_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WardrobeItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_wardrobe_item_photo_wardrobe_items__item_id__photo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_replace_wardrobe_item_photo_wardrobe_items__item_id__photo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_wardrobe_item_wardrobe_items_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_wardrobe_item_wardrobe_items_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_wardrobe_item_wardrobe_items_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWardrobeItemFromUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WardrobeItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_preferences_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitFeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionFeedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceProfile"];
                };
            };
        };
    };
    clear_preferences_preferences_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_preference_signal_preferences_signals__signal_key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
